# Generated by Django 3.0.7 on 2020-06-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='friends',
        ),
    ]
